name: Testing Suite
on: [push, pull_request] # Run on Push and Pull Requests

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          # Maps TCP port 5432 on service container to the host
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.3.0
      - name: pnpm Install
        run: pnpm install
      - name: Build Packages
        run: pnpm --filter "./packages/**" build
      # - name: Setup DB
      #   run: pnpm --filter @reubin/graphql-api db:push 
      #   env:
      #     # The hostname used to communicate with the PostgreSQL service container
      #     POSTGRES_HOST: postgres
      #     # The default PostgreSQL port
      #     POSTGRES_PORT: 5432
      #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      - name: Test
        run: pnpm test
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public